---
apiVersion: "v1"
kind: "List"
items:

  - apiVersion: "v1"
    kind: "Namespace"
    metadata:
      name: "jenkins"
      labels:
        name: "jenkins"

  - apiVersion: "v1"
    kind: "PersistentVolumeClaim"
    metadata:
      name: "jenkins"
      namespace: "jenkins"
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 5Gi

  - apiVersion: "extensions/v1beta1"
    kind: "Deployment"
    metadata:
      name: "jenkins"
      namespace: "jenkins"
      labels:
        name: "jenkins"
    spec:
      replicas: 1
      template:
        metadata:
          labels:
            name: "jenkins"
        spec:
          containers:
            - name: "jenkins"
              image: "microsoft/java-on-azure-jenkins-master:0.5"
              ports:
                - containerPort: 8080
                - containerPort: 50000
              resources:
                limits:
                  cpu: 1
                  memory: 4Gi
                requests:
                  cpu: 1
                  memory: 2Gi
              env:
                - name: CPU_REQUEST
                  valueFrom:
                    resourceFieldRef:
                      resource: requests.cpu
                - name: CPU_LIMIT
                  valueFrom:
                    resourceFieldRef:
                      resource: limits.cpu
                - name: MEM_REQUEST
                  valueFrom:
                    resourceFieldRef:
                      resource: requests.memory
                      divisor: "1Mi"
                - name: MEM_LIMIT
                  valueFrom:
                    resourceFieldRef:
                      resource: limits.memory
                      divisor: "1Mi"
                - name: GITHUB_REPO_OWNER
                  valueFrom:
                    configMapKeyRef:
                     name: my-config
                     key: githubRepoOwner
                - name: GITHUB_REPO_NAME
                  valueFrom:
                    configMapKeyRef:
                     name: my-config
                     key: githubRepoName
                - name: JENKINS_PASSWORD
                  valueFrom:
                    secretKeyRef:
                     name: my-secrets
                     key: jenkinsPassword
                - name: GROUP_SUFFIX
                  valueFrom:
                    configMapKeyRef:
                     name: my-config
                     key: groupSuffix
              volumeMounts:
                - name: "kube"
                  mountPath: "/root/.kube"
                - name: "kube-azure"
                  mountPath: "/etc/kubernetes"
                - name: "docker"
                  mountPath: "/var/run/docker.sock"
                - name: "jenkins-home"
                  mountPath: "/var/jenkins_home"
                - name: "ssh-key"
                  mountPath: "/root/.ssh"
              readinessProbe:
                httpGet:
                  path: /login
                  port: 8080
                initialDelaySeconds: 60
                periodSeconds: 5
          securityContext:
            fsGroup: 1000
          volumes:
            - name: "kube"
              hostPath:
                path: "/root/.kube"
            - name: "kube-azure"
              hostPath:
                path: "/etc/kubernetes"
            - name: "docker"
              hostPath:
                path: "/var/run/docker.sock"
            - name: "jenkins-home"
              persistentVolumeClaim:
                claimName: "jenkins"
            - name: "ssh-key"
              secret:
                secretName: "my-secrets"
                items:
                  - key: "sshKey"
                    path: "id_rsa"

  - apiVersion: "v1"
    kind: "Service"
    metadata:
      name: "jenkins"
      namespace: "jenkins"
    spec:
      type: "LoadBalancer"
      selector:
        name: "jenkins"
      ports:
        - name: "http"
          port: 80
          targetPort: 8080
          protocol: "TCP"
        - name: "slave"
          port: 50000
          protocol: "TCP"
