INSERT INTO movies VALUES (1, 'Inception (2010)', 9.7, 'This is the description.', '');
INSERT INTO movies VALUES (2, 'Goodfellas (1990)', 9.7, 'This is the description.', '');
INSERT INTO movies VALUES (3, 'The Usual Suspects (1995)', 9.6, 'This is the description.', '');
INSERT INTO movies VALUES (4, 'The Matrix (1999)', 8.8, 'This is the description.', '');
INSERT INTO movies VALUES (5, 'Saving Private Ryan (1998)', 8.5, 'This is the description.', '');
INSERT INTO movies VALUES (6, 'Cera una volta il West (1968)', 8.5, 'This is the description.', '');
INSERT INTO movies VALUES (7, 'American History X (1998)', 8.5, 'This is the description.', '');
INSERT INTO movies VALUES (8, 'Shichinin no samurai (1954)', 8.5, 'This is the description.', '');
INSERT INTO movies VALUES (9, 'Star Wars (1977)', 8.4, 'This is the description.', '');
INSERT INTO movies VALUES (10, 'Sen to Chihiro no kamikakushi (2001)', 8.4, 'This is the description.', '');
INSERT INTO movies VALUES (11, 'The Departed (2006)', 8.4, 'This is the description.', '');
INSERT INTO movies VALUES (12, 'Rear Window (1954)', 8.4, 'This is the description.', '');
INSERT INTO movies VALUES (13, 'The Pianist (2002)', 8.4, 'This is the description.', '');
INSERT INTO movies VALUES (14, 'The Dark Knight (2008)', 8.4, 'This is the description.', '');
INSERT INTO movies VALUES (15, '12 Angry Men (1957)', 8.4, 'This is the description.', '');
INSERT INTO movies VALUES (16, 'Modern Times (1936)', 8.1, 'This is the description.', '');
INSERT INTO movies VALUES (17, 'Schindler s List (1993)', 8.1, 'This is the description.', '');
INSERT INTO movies VALUES (18, 'The Silence of the Lambs (1991)', 8.1, 'This is the description.', '');
INSERT INTO movies VALUES (19, 'The Green Mile (1999)', 8.1, 'This is the description.', '');
INSERT INTO movies VALUES (20, 'Raiders of the Lost Ark (1981)', 8.1, 'This is the description.', '');
INSERT INTO movies VALUES (21, 'Pulp Fiction (1994)', 8.1, 'This is the description.', '');
INSERT INTO movies VALUES (22, 'Star Wars: Episode V - The Empire Strikes Back (1980)', 7.7, 'This is the description.', '');
INSERT INTO movies VALUES (23, 'Forrest Gump (1994)', 7.7, 'This is the description.', '');
INSERT INTO movies VALUES (24, 'Back to the Future (1985)', 7.5, 'This is the description.', '');
INSERT INTO movies VALUES (25, 'Gladiator (2000)', 7.5, 'This is the description.', '');
INSERT INTO movies VALUES (26, 'Memento (2000)', 7.5, 'This is the description.', '');
INSERT INTO movies VALUES (27, 'Apocalypse Now (1979)', 6.5, 'This is the description.', '');
INSERT INTO movies VALUES (28, 'It s a Wonderful Life (1946)', 6.5, 'This is the description.', '');
INSERT INTO movies VALUES (29, 'Interstellar (2014)', 6.5, 'This is the description.', '');
INSERT INTO movies VALUES (30, 'City Lights (1931)', 5.5, 'This is the description.', '');
INSERT INTO movies VALUES (31, 'Cidade de Deus (2002)', 5.4, 'This is the description.', '');
INSERT INTO movies VALUES (32, 'The Godfather (1972)', 5.2, 'This is the description.', '');
INSERT INTO movies VALUES (33, 'The Godfather: Part II (1974)', 5.0, 'This is the description.', '');
INSERT INTO movies VALUES (34, 'Casablanca (1942)', 4.5, 'This is the description.', '');
INSERT INTO movies VALUES (35, 'Whiplash (2014)', 4.5, 'This is the description.', '');