apiVersion: v1
kind: Secret
metadata:
  name: ${docker.image.prefix}
  namespace: ${target.environment}
  annotations:
    maven.fabric8.io/dockerServerId: ${docker.image.prefix}
type: kubernetes.io/dockercfg